chore: documentate the latest react-native bridge changes
smartlook/smartlook.github.io pull request #245
Opened 2021-05-13 15:13 UTC by krystofcelba

2021-05-13 15:38 UTC, adamblack requested changes

2021-05-13 15:38 UTC, adamblack commented on src/api_reference.mdx
> +To simplify handling sensitive/not sensitive views in React Native we have prepared nice declarative ways to do it.
handling of ...

2021-05-17 16:28 UTC, Acro approved these changes

2021-05-17 16:29 UTC, adamblack approved these changes

2021-05-17 16:29 UTC, merged