iOS SDK Release 1.8.3
smartlook/smartlook.github.io pull request #287
Opened 2021-12-04 12:05 UTC by pavel-kroh-smartlook

Just new changelog entry and new link to dowload.

2021-12-06 08:01 UTC, vaclav-halik-smartlook requested changes
Fix typos please. Thanks.

2021-12-06 08:45 UTC, pavel-kroh-smartlook commented on src/sdk-installation/changelogs.mdx
> +- Ocassional crashes caused by \`EXC_BAD_ACCESS KERN_INVALID_ADDRESS\`.
Fixed.

2021-12-06 08:47 UTC, pavel-kroh-smartlook commented on src/sdk-installation/changelogs.mdx
> +- Safer handling of video pixel buffer pool to avoid \`Fatal Exception: NSInternalInconsistencyException\` crashes with uncertain true cause.
Reworded.

2021-12-07 07:23 UTC, vaclav-halik-smartlook reviewed
OK

2021-12-07 07:24 UTC, vaclav-halik-smartlook approved these changes

2021-12-07 07:24 UTC, merged