Feat delete endpoints
smartlook/smartlook.github.io pull request #293
Opened 2021-12-21 12:59 UTC by Blackman37

2022-01-05 08:27 UTC, janzal requested changes

2022-01-05 08:27 UTC, janzal commented on src/rest-api/cookbook.mdx
> +1. Check out the [API reference](/docs/rest-api/reference)
Tenhle krok bych klidne vynechal.

2022-01-05 08:27 UTC, janzal commented on src/rest-api/cookbook.mdx
> +    1. Delete only 1 visitor by `visitorId` (unique ID obtained by Smartlook) - this `visitorId` fill in to the path
Tady bych pridal i tu konkretni cestu z dokumentace. Stejne tak u dalsiho bodu.

2022-01-05 08:27 UTC, janzal commented on src/rest-api/cookbook.mdx
> +    2. Delete more visitors by `userId` (`UserId` is a value, which is obtained from the recorded page, where you can set this ID)
Vsechny `userId` by mely byt v cammelCase.

A jeste nejak upravit tu dalsi vetu, pridal bych tam odkaz na https://docs.smartlook.com/docs/web/identify-visitor?platform=web 

```suggestion
    2. Delete more visitors by `userId` (`userId` is set by identify method in the SDK)
```

2022-01-05 08:27 UTC, janzal commented on src/rest-api/cookbook.mdx
> +2. Are existing 2 endpoints for deleting visitors and their related events, sessions...
```suggestion
2. There are 2 endpoints to delete visitors and their related events and sessions
```

2022-01-07 12:30 UTC, Blackman37 commented on src/rest-api/cookbook.mdx
> +    1. Delete only 1 visitor by `visitorId` (unique ID obtained by Smartlook) - this `visitorId` fill in to the path
Doplneno

2022-01-18 08:53 UTC, janzal approved these changes

2022-01-18 08:53 UTC, merged